# Generated by Django 2.0.6 on 2018-10-29 03:04

import apps.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Aprender',
                'verbose_name_plural': 'Aprender',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Cliente')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.web.models.upload_location, verbose_name='Imagen', width_field='width_field')),
                ('height_field', models.IntegerField(default=400)),
                ('width_field', models.IntegerField(default=400)),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de suscripción')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('mensaje', models.TextField(max_length=255, verbose_name='Mensaje')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de suscripción')),
            ],
            options={
                'verbose_name': 'Suscrito',
                'verbose_name_plural': 'Suscritos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('nosotros', models.TextField(verbose_name='Nosotros')),
                ('aprenderas_slogan', models.CharField(max_length=255, verbose_name='Aprenderás Slogan')),
                ('aprender_id', models.ManyToManyField(to='web.Aprender')),
            ],
            options={
                'verbose_name': 'Web',
                'verbose_name_plural': 'Webs',
            },
        ),
    ]
