# Generated by Django 2.0.6 on 2018-09-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aprender',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slogan', models.CharField(max_length=255, verbose_name='Slogan')),
                ('nosotros', models.TextField(verbose_name='Nosotros')),
                ('aprenderas_slogan', models.CharField(max_length=255, verbose_name='Aprenderás Slogan')),
                ('aprender_id', models.ManyToManyField(to='web.Aprender')),
            ],
        ),
    ]
