# Generated by Django 2.0.6 on 2018-09-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Cliente')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
            ],
        ),
    ]
