# Generated by Django 2.0.6 on 2018-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=1, verbose_name='Estado'),
            preserve_default=False,
        ),
    ]
