# Generated by Django 2.0.6 on 2018-09-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Estado'),
        ),
    ]
