# Generated by Django 2.0.6 on 2018-09-12 06:59

import apps.web.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180912_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='height_field',
            field=models.IntegerField(default=400),
        ),
        migrations.AddField(
            model_name='cliente',
            name='url_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=apps.web.models.upload_location, verbose_name='Imagen', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='width_field',
            field=models.IntegerField(default=400),
        ),
    ]
