# Generated by Django 2.0.6 on 2018-09-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20180912_0159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
            ],
        ),
    ]
