# Generated by Django 2.0.6 on 2018-09-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de Cliente')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('mensaje', models.TextField(max_length=255, verbose_name='Mensaje')),
            ],
        ),
    ]
