# Generated by Django 2.0.6 on 2018-10-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
    ]
