# Generated by Django 2.0.6 on 2018-10-08 21:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.CharField(max_length=255, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('estado', models.BooleanField(default=False, verbose_name='Activo o No Activo')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['id'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='persona',
            name='comentarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Comentario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(to='blog.Comentario'),
        ),
        migrations.AddField(
            model_name='autor',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
            preserve_default=False,
        ),
    ]
