# Generated by Django 2.0.6 on 2018-10-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181008_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='comentarios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comentario'),
        ),
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Comentario'),
        ),
    ]
