# Generated by Django 2.0.6 on 2018-10-08 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181008_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Autor'),
            preserve_default=False,
        ),
    ]
