# Generated by Django 2.0.6 on 2018-10-08 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181008_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='blog.Comentario'),
        ),
    ]
