# Generated by Django 2.0.6 on 2018-10-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181008_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='imagen_previa',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
