# Generated by Django 2.0.6 on 2018-10-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181008_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=170, verbose_name='Descripción'),
        ),
    ]
