# Generated by Django 2.0.6 on 2018-10-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181008_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen_previa',
            field=models.URLField(max_length=255),
        ),
    ]
