# Generated by Django 2.0.6 on 2018-10-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181011_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_pasada',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fecha pasada'),
        ),
    ]
