# Generated by Django 2.0.6 on 2018-10-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_fecha_pasada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de creación'),
        ),
    ]
