# Generated by Django 2.0.6 on 2018-10-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20181026_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descripción'),
        ),
    ]
